### ISSUE TITLE
Bring back esbuild in Fedora package build

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit-files#508]
cc @martinpitt 

Fedora won't accept us unless we esbuild the package on their infra.  Fair enough.  We dropped that in #505 because I was mostly copying from what cockpit-machines was doing, which doesn't require this (because it's grandfathered in).

Before we bring it back, let's talk about it a bit: if we're going to be building from source as part of the package build, then it probably doesn't make sense to separate the node-cache tarball from the main one.  Can we just have one giant tarball?

Can we include esbuild in that tarball, but not eslint, stylelint, typescript, etc?  Or would Fedora prefer to use its own esbuild package, anyway?

**Comment by martinpitt** [comment]
>  Can we just have one giant tarball?

That's not useful for users who install from upstream, or distros which don't require a rebuild. We even *can't* rebuild it in RHEL 8, as there's some missing dependency, see https://github.com/cockpit-project/starter-kit/blob/main/packaging/cockpit-starter-kit.spec.in#L35. It doesn't hurt to have a separate one IMHO.

> Can we include esbuild in that tarball, but not eslint, stylelint, typescript, etc?

That'd be nice, but we'd then have to track two separate node_modules git, or install the linters in some other way. It feels too complicated to me, but if you have an idea, sure.

> Or would Fedora prefer to use its own esbuild package, anyway?

I would actually prefer that too, and when we started with introducing esbuild, I spent some hours trying to do that. It failed because the shipped rpm is lacking all the bits to run esbuild as a js module, you just have the CLI. And installing these from npm fails due to strict version dependencies -- as soon as the Fedora package updates, or you try to build it in a different distro, it fails. This all sucks :cry:

**Comment by jelly** [comment]
> > Can we just have one giant tarball?
> 
> That's not useful for users who install from upstream, or distros which don't require a rebuild. We even _can't_ rebuild it in RHEL 8, as there's some missing dependency, see https://github.com/cockpit-project/starter-kit/blob/main/packaging/cockpit-starter-kit.spec.in#L35. It doesn't hurt to have a separate one IMHO.

Plus this is imo a nice separation of concerns. Our code and vendored code. The most recent Cockpit "plugin" which got accepted into Fedora is [anaconda-webui](https://src.fedoraproject.org/rpms/anaconda-webui/blob/rawhide/f/anaconda-webui.spec). Which interestingly was allowed to ship a "build tarball" with the `dist` folder.
 
> > Can we include esbuild in that tarball, but not eslint, stylelint, typescript, etc?
> 
> That'd be nice, but we'd then have to track two separate node_modules git, or install the linters in some other way. It feels too complicated to me, but if you have an idea, sure.

I don't think this is going to give us much, except more pain because we have three different ways of building Cockpit plugins in a Distro.
 
> > Or would Fedora prefer to use its own esbuild package, anyway?
> 
> I would actually prefer that too, and when we started with introducing esbuild, I spent some hours trying to do that. It failed because the shipped rpm is lacking all the bits to run esbuild as a js module, you just have the CLI. And installing these from npm fails due to strict version dependencies -- as soon as the Fedora package updates, or you try to build it in a different distro, it fails. This all sucks 😢

Right, the esbuild plugins we use have a very strict dependency on esbuild.

**Comment by allisonkarlitskaya** [comment]
> That'd be nice, but we'd then have to track two separate node_modules git, or install the linters in some other way. It feels too complicated to me, but if you have an idea, sure.

So in a project like ours (ie: not published in npmjs), depends vs. dev-depends really makes absolutely no difference, and there's a lot of stuff that sort of sits on the fence, like the recently added language maps (which are, in some form, included in the bundle, but not exactly).

We could make the "depends" section be exactly the stuff required to run `./build.js` and the "dev depends" be all the linters and such.

**Comment by allisonkarlitskaya** [comment]
> I would actually prefer that too, and when we started with introducing esbuild, I spent some hours trying to do that. It failed because the shipped rpm is lacking all the bits to run esbuild as a js module, you just have the CLI. And installing these from npm fails due to strict version dependencies -- as soon as the Fedora package updates, or you try to build it in a different distro, it fails. This all sucks 😢

On second thought: from a reproducible standpoint, I prefer that the esbuild used upstream and in the distro is the same, actually...

**Comment by martinpitt** [comment]
> depends vs. dev-depends really makes absolutely no difference

Functionally not, but it does wrt. rpm declarations. See https://github.com/cockpit-project/cockpit/commit/940cc5cd1d059c4cab. 

> We could make the "depends" section be exactly the stuff required to run ./build.js and the "dev depends" be all the linters and such.

No objection if it helps, as long as `NPM_PROVIDES` filter out the build dependencies and only leave the *actual* runtime dependencies (such as React and PF). This sounds a bit brittle, though.

> from a reproducible standpoint, I prefer that the esbuild used upstream and in the distro is the same, actually...

Yeah, me too -- but *if* we can make it work with the Fedora package, then that would go into our tasks container, and thus it stays mostly reproducible.

Wrt. the Fedora policy, please see https://bugzilla.redhat.com/show_bug.cgi?id=1969450 -- that triggered this whole stuff. See https://docs.fedoraproject.org/en-US/packaging-guidelines/JavaScript/#_compilationminification :

> If a JavaScript library typically is shipped as minified or compiled code, it MUST be compiled or minified as part of the RPM build process. Shipping pre-minified or pre-compiled code is unacceptable in Fedora.
